### ISSUE TITLE
Setup Apollo GraphQL With TypeScript 

### ISSUE THREAD

**Issue by pavankpdev** [DuolearnHQ/ArtPlace#1]
We need to set up Apollo GraphQL with TypeScript in our project. This will involve installing the necessary dependencies, configuring the Apollo server, and creating the necessary types and resolvers. The implementation should also include authentication and error handling. This issue is a part of our larger goal to build a GraphQL API for our project. 

Acceptance Criteria:
- Apollo GraphQL server should be set up with TypeScript
- All necessary dependencies should be installed and configured
- Authentication and error handling should be implemented
- Types and resolvers should be created
- API should be fully functional and tested
- An example ENV file should be created
- Pre-Commit hooks should be configured

**Comment by pavankpdev** [comment]
@devnm21 Please review PR #10

**Comment by RwandaGloria** [comment]
Hi Pavan! I am interested in working in this issue. Why? Because I have great knowledge in Express, however I haven't worked with GraphQL and I'm very much interested in working eith it. I'd like to use this opportunity to learn as much as I can. Thanks for the opportunity and I hope you can accept me to work on this issue.

**Comment by pavankpdev** [comment]
Hey @RwandaGloria This issue was setting up the project and It's already completed, you can check out this issue #5. 
This issue is related to GraphQL and you'll be working on developing Auth resolvers
